# syntax=docker/dockerfile:1

# --- deps (instala dependências com cache) ---
FROM node:20-alpine AS deps
WORKDIR /app

# Necessário para alguns pacotes nativos (caso existam)
RUN apk add --no-cache libc6-compat

COPY package.json package-lock.json ./
RUN npm ci

# --- build ---
FROM node:20-alpine AS builder
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

# NEXT_PRIVATE_* vars must be available at build time
ARG NEXT_PRIVATE_API_BASE_URL
ARG NEXT_PRIVATE_SOCKET_URL
ARG NEXT_PRIVATE_TOKEN_CLOUDFLARE
ARG NEXT_PRIVATE_CLOUDFLARE_D1_UUID
ARG NEXT_PRIVATE_CLOUDFLARE_D1_DATABASE
ARG NEXT_PRIVATE_CLOUDFLARE_D1_TABLE
ARG NEXT_PRIVATE_GOOGLE_OAUTH_ID
ARG NEXT_PRIVATE_GOOGLE_OAUTH_KEY

ENV NEXT_PRIVATE_API_BASE_URL=$NEXT_PRIVATE_API_BASE_URL
ENV NEXT_PRIVATE_SOCKET_URL=$NEXT_PRIVATE_SOCKET_URL
ENV NEXT_PRIVATE_TOKEN_CLOUDFLARE=$NEXT_PRIVATE_TOKEN_CLOUDFLARE
ENV NEXT_PRIVATE_CLOUDFLARE_D1_UUID=$NEXT_PRIVATE_CLOUDFLARE_D1_UUID
ENV NEXT_PRIVATE_CLOUDFLARE_D1_DATABASE=$NEXT_PRIVATE_CLOUDFLARE_D1_DATABASE
ENV NEXT_PRIVATE_CLOUDFLARE_D1_TABLE=$NEXT_PRIVATE_CLOUDFLARE_D1_TABLE
ENV NEXT_PRIVATE_GOOGLE_OAUTH_ID=$NEXT_PRIVATE_GOOGLE_OAUTH_ID
ENV NEXT_PRIVATE_GOOGLE_OAUTH_KEY=$NEXT_PRIVATE_GOOGLE_OAUTH_KEY

COPY --from=deps /app/node_modules ./node_modules
COPY . .

RUN npm run build

# --- runner ---
FROM node:20-alpine AS runner
WORKDIR /app

# Set timezone to Brazil (UTC-3)
ENV TZ=America/Sao_Paulo
RUN apk add --no-cache tzdata

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

# NEXT_PRIVATE_* vars (baked at build, but can be overridden at runtime)
ARG NEXT_PRIVATE_API_BASE_URL
ARG NEXT_PRIVATE_SOCKET_URL
ARG NEXT_PRIVATE_TOKEN_CLOUDFLARE
ARG NEXT_PRIVATE_CLOUDFLARE_D1_UUID
ARG NEXT_PRIVATE_CLOUDFLARE_D1_DATABASE
ARG NEXT_PRIVATE_CLOUDFLARE_D1_TABLE
ARG NEXT_PRIVATE_GOOGLE_OAUTH_ID
ARG NEXT_PRIVATE_GOOGLE_OAUTH_KEY

ENV NEXT_PRIVATE_API_BASE_URL=$NEXT_PRIVATE_API_BASE_URL
ENV NEXT_PRIVATE_SOCKET_URL=$NEXT_PRIVATE_SOCKET_URL
ENV NEXT_PRIVATE_TOKEN_CLOUDFLARE=$NEXT_PRIVATE_TOKEN_CLOUDFLARE
ENV NEXT_PRIVATE_CLOUDFLARE_D1_UUID=$NEXT_PRIVATE_CLOUDFLARE_D1_UUID
ENV NEXT_PRIVATE_CLOUDFLARE_D1_DATABASE=$NEXT_PRIVATE_CLOUDFLARE_D1_DATABASE
ENV NEXT_PRIVATE_CLOUDFLARE_D1_TABLE=$NEXT_PRIVATE_CLOUDFLARE_D1_TABLE
ENV NEXT_PRIVATE_GOOGLE_OAUTH_ID=$NEXT_PRIVATE_GOOGLE_OAUTH_ID
ENV NEXT_PRIVATE_GOOGLE_OAUTH_KEY=$NEXT_PRIVATE_GOOGLE_OAUTH_KEY

# Server-side only credentials (set at runtime via docker run -e or docker-compose)
ENV NEXTAUTH_SECRET=""
ENV NEXTAUTH_URL=""
ENV CLOUDFLARE_ACCOUNT_ID=""
ENV CLOUDFLARE_D1_UUID=""
ENV CLOUDFLARE_D1_TOKEN=""
ENV GOOGLE_CLIENT_ID=""
ENV GOOGLE_CLIENT_SECRET=""

# Cria usuário não-root
RUN addgroup -S nextjs ; adduser -S nextjs -G nextjs

# Copia apenas o necessário para executar
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/package-lock.json ./package-lock.json

# Instala apenas dependências de produção
RUN npm ci --omit=dev && npm cache clean --force

COPY --from=builder /app/next.config.js ./next.config.js
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next ./.next

USER nextjs

EXPOSE 3000

# Render define PORT. Garante bind 0.0.0.0 dentro do container.
CMD ["sh", "-c", "node ./node_modules/next/dist/bin/next start -H 0.0.0.0 -p ${PORT:-3000}"]
